### ISSUE TITLE
tox-runner

### ISSUE THREAD

**Issue by tbekolay** [pytest-dev/pytest-runner#14]
`tox` has a similar [`setuptools` command](http://tox.readthedocs.org/en/latest/example/basic.html#integration-with-setuptools-distribute-test-commands). Making a similar `tox-runner` package would probably duplicate a lot of what's in this project.

Do you think there would be a way to incorporate running `tox` with `python setup.py test` in this project? Or should this be done as a separate project despite the possible overlap?

**Comment by jaraco** [comment]
I think a tox-runner package would be substantially different from a pytest-runner package. A tox runner package doesn't need to download any packages other than tox... so the `setup_requires` and `install_requires` and `extras` are not relevant, as tox will be creating its own environments and python instances and installing the requisite dependencies to those environments. pytest-runner, on the other hand, aims to run against the current Python interpreter with the necessary dependencies for the tests and the project and (optionally) the extras.

I'm willing to consider incorporating tox runner support into this project for the sake of minimizing packages.

How do you imagine the tox-runner would work?

**Comment by tbekolay** [comment]
You're right, the `setup.py` would be substantially different. Most of the duplication I'm anticipating would be in the `PyTest` class itself, but given that the duplication would only be a few dozen lines of code, it is likely not worth putting both things in repo.

It should only take a few hours to make a `tox-runner` repo, so I will spin that up and see how much duplication there actually is. I'll send the link once that's done so we can evaluate whether they make more sense separate or together.
