### ISSUE TITLE
no copyright/license included with source

### ISSUE THREAD

**Issue by brianmay** [pytest-dev/pytest-runner#16]
Apparently it is MIT licensed, there is nothing I can see with the source to confirm this. Such as a copy of the MIT license for example.

**Comment by jaraco** [comment]
It is MIT Licensed, which is [declared in the source](https://github.com/pytest-dev/pytest-runner/blob/master/setup.py#L43) and further [reflected and searchable by license in the metadata](https://pypi.python.org/pypi/pytest-runner). I choose not to create a copy of the license with the source as I feel a reference to a common license is adequate.

**Comment by flub** [comment]
Erm, we do actually ask for all projects under pytest-dev to include a LICENSE or LICENSE.txt file in the toplevel (https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#submitting-plugins-to-pytest-dev).  Apologies for missing this earlier but it would be really appreciated if you could add this anyway.

Thanks,
Floris

**Comment by jaraco** [comment]
Those docs are specifically about plugins, so it's arguable that those guidelines don't apply to this repo, which violates other provisions there (uses README.rst instead of README.txt and doesn't have a tox.ini). Given the preference by pytest-dev, I'll reluctantly accept a PR to correct the issue, but I won't be spending any time on it myself.

**Comment by flub** [comment]
Sure this is no plugin, but I don't think that makes it exempt from the pytest-dev guidelines.  And a README by whatever extension is fine.  Anyway, I've created a PR now: https://github.com/pytest-dev/pytest-runner/pull/17

As for a tox.ini, this surely is more work but it would still be good to add.  It seems currently there's no automated tests at all which is something we where trying to avoid in pytest-dev.
