### ISSUE TITLE
Ignore files with testpaths

### ISSUE THREAD

**Issue by maxkoryukov** [pytest-dev/pytest-runner#19]
Hello!

## subject

I run `python setup.py pytest` or `python setup.py test` (does not matter which) and `testpaths` option from `setup.cfg` doesn't work. As a consequence, I am getting testing results for **all** subdirectories (but I need test-results just for **one** dir, described further).

So:
* `python setup.py pytest` runs ALL tests (even excluded)
* `python libs/pytest.py` runs required set of tests (in `memorybuffer` folder)

I tried to use `python_files` option. But it doesn't change anything.

## details

I have the following file structure:

```
/project
    + setup.py
    + setup.cfg
    /memorybuffer
        + __init__.py
        + file.py
        + file_test.py
    /libs
        + pytest.py
        + pep8.py
        /pyflakes
            # 
            # PYFLAKES FILES, with tests
            # 
        /_pytest
            # PYTEST files
       
```

**The content in `libs` folder is generated** during installation: `pip install -r requirements-dev.txt -t libs`

Here is my `setup.cfg`:
```ini
[aliases]
test=pytest

[tool:pytest]
testpaths=./memorybuffer/
#python_files = memorybuffer/*/*.py

[tool:test]
testpaths=./memorybuffer/
#python_files = memorybuffer/*/*.py
```

My `setup.cfg`:
```python
from setuptools import setup

setup(
    setup_requires=['pytest-runner', 'setuptools-pep8'],
    tests_require=['pytest']
)
```

## environment

* Python 2.7.6
* pip 8.1.2
* pytest version 3.0.0

**Comment by jaraco** [comment]
When you run with pytest-runner, are you sure that pytest 3.0.0 is being invoked? The `tool:pytest` support is brand new. I suspect if you put that setting in a `[pytest]` section in `pytest.ini`, that it will work with older pytest versions as well. Or you might be able to pin a later version of pytest in your setup_requires.

**Comment by maxkoryukov** [comment]
@jaraco , thanks. I had global `pytest` 2.8.7

`[sudo] pip install --upgrade pytest` was all I need
