### ISSUE TITLE
Change command name to simply 'pytest'

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest-runner#2]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

In discussions with @hpk42, it sounds as if using the command name 'pytest' would be preferable, and that change would likely be sufficient to justify making pytest-runner the recommended technique for invoking pytest under setuptools.

---
- Bitbucket: https://bitbucket.org/pytest-dev/pytest-runner/issue/2

**Comment by felixonmars** [comment]
Hi, sorry for bumping an old thread. I see that last comment mentioned some issue about setup.cfg, is it still an issue? I am asking because I want to determine which command I should use in the build scripts (`ptr` or `pytest`?).

**Comment by jaraco** [comment]
Definitely pytest. Ptr is there for compatibility and will be removed soon.

**Comment by felixonmars** [comment]
I see, thanks!
