### ISSUE TITLE
README points to jaraco.collections which no longer seems to use pytest-runner

### ISSUE THREAD

**Issue by icemac** [pytest-dev/pytest-runner#24]
[README.rst#L56](https://github.com/pytest-dev/pytest-runner/blame/master/README.rst#L56) points to jaraco.collections as a real world example. But its [setup.py](https://github.com/jaraco/jaraco.collections/blob/master/setup.py) does not use pytest-runner.

Is there another real world example?

**Comment by jaraco** [comment]
Oh dear. Yes, that's a bug in the readme.

I ran [this search on Github](https://github.com/search?utf8=%E2%9C%93&q=filename%3Asetup.py+pytest-runner&type=Code&ref=searchresults) which should serve as a possible reference to real-world usage. I'll update the readme accordingly.
