### ISSUE TITLE
Support verbose option

### ISSUE THREAD

**Issue by skirpichev** [pytest-dev/pytest-runner#29]
Currently, global ``-v`` options doesn't affect pytest output.

**Comment by jaraco** [comment]
All options to pytest need to be passed through the `--addopts` parameter. e.g.

```
python setup.py pytest --addopts='-v'
```

The options to ptr (or the distutils `pytest` command) are especially constrained, which is why all arguments passed through to pytest need to be in a single argument.

**Comment by skirpichev** [comment]
> All options to pytest need to be passed through the --addopts parameter.

I know, that that's possible, but I doubt it should be so in this particular case.  Some other plugins reuse this global option to control output.

**Comment by jaraco** [comment]
I see. You're suggesting that `pytest-runner` should use the `--verbose` option to the distutils command and relay that to the pytest invocation.

I don't think we want to introduce this behavior. It adds complexity to the code and use-cases (considering what should happen if one passes `-v` to distutils but then `-q` to pytest, or `-v` to both).

I think it's better to maintain the separation of concerns, so `-v` to the distutils command applies to output of the distutils commands and `-v` to the pytest invocation applies to the output of the pytest run, and the two have no interaction. In this way, it clear where options should go to create verbose output for one or the other command, and you have to specify `-v` twice if you want both to be verbose.

So I'm strongly inclined to go wontfix on this one, but if you can provide a compelling case where you would gain a lot of value from the pytest run adopting the verbosity setting from the distutils command, then please share it here and I'll reconsider.
