### ISSUE TITLE
How to run multiple isolated tests?

### ISSUE THREAD

**Issue by kravemir** [pytest-dev/pytest-runner#35]
I've got multiple test folders - 'tests', 'tests_integration', 'tests_integration2',... Integration tests use different betamax/session configurations. And, they collide, if they are run together with: `python -m pytest`

I need to run each test folder individually:

* `python -m pytest tests`
* `python -m pytest tests_integration`
* `python -m pytest tests_integration2`

How can I achieve this with `pytest-runner`?

**Comment by jaraco** [comment]
Anything in `--addopts` is passed through to pytest, so

`python setup.py pytest --addopts='tests'`

**Comment by kravemir** [comment]
I have discovered it literally 30 seconds ago. Thanks for response, anyway.
