### ISSUE TITLE
Code not pep8 compliant due to the usage of tabs instead of spaces

### ISSUE THREAD

**Issue by WoLpH** [pytest-dev/pytest-runner#36]
A build on one of my projects just failed because pytest-runner uses tabs instead of spaces as indentation: https://travis-ci.org/WoLpH/python-progressbar/jobs/310044371

It seems that the latest version of the pep8 tool doesn't allow for tabs anymore: https://pypi.python.org/pypi/pep8

**Comment by jaraco** [comment]
Tabs are my preference and they're fine. Just disable W191 in your editor and your projects. Unfortunately, to the best of my knowledge, pep8 doesn't provide an effective way to exclude a package or file, but only has user-local and per-project settings. If it's possible to add one line to the runner package to work around the issue, I'd entertain that, but I don't want to go converting tabs to spaces in this project and start down the slippery slope of converting all my projects (ruining the blame history and accepting the inferior multi-byte symbol for indentation).
