### ISSUE TITLE
[Py3.3] AttributeError: type object 'test' has no attribute 'install_dists'

### ISSUE THREAD

**Issue by juanshishido** [pytest-dev/pytest-runner#39]
Hello. I'm seeing the following [build failure](https://travis-ci.org/twitterdev/twitter-python-ads-sdk/jobs/346166016) with Python 3.3:

```
Installed /home/travis/build/twitterdev/twitter-python-ads-sdk/.eggs/pytest_runner-4.0-py3.3.egg
running pytest
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    **extra_opts
  File "/opt/python/3.3.6/lib/python3.3/distutils/core.py", line 147, in setup
    dist.run_commands()
  File "/opt/python/3.3.6/lib/python3.3/distutils/dist.py", line 930, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.3.6/lib/python3.3/distutils/dist.py", line 949, in run_command
    cmd_obj.run()
  File "/home/travis/build/twitterdev/twitter-python-ads-sdk/.eggs/pytest_runner-4.0-py3.3.egg/ptr.py", line 157, in run
  File "/home/travis/build/twitterdev/twitter-python-ads-sdk/.eggs/pytest_runner-4.0-py3.3.egg/ptr.py", line 118, in install_dists
AttributeError: type object 'test' has no attribute 'install_dists'
The command "python setup.py test" exited with 1.
```

Looks like it may be related to [this change](https://github.com/pytest-dev/pytest-runner/commit/ac9482d95d48a66c80e2f10bdbf4e6cbef571c36#diff-b45bdc6847c1b460b72aae78d80c5ff9R118).

Any suggestions on how to resolve this?

Thank you.

**Comment by RonnyPfannschmidt** [comment]
whats your setuptools version?

**Comment by bilderbuchi** [comment]
I am also seeing this, with setuptools 21.2.1/py35, setuptools 23.0.0/py34, but not with setuptool 38.5.1/py36. See [this CI build](https://travis-ci.org/ralph-group/pymeasure/builds/354710347). Differences in versions are apparently because of differently specified dev requirements for the different versions.

**Comment by jaraco** [comment]
That's right. The 4.0 release [intentionally dropped support](http://pytest-runner.readthedocs.io/en/latest/history.html) for those older setuptools versions. The workaround is to pin pytest-runner to older versions until later setuptools versions can be expected in your environment.

**Comment by bilderbuchi** [comment]
I see. Why is this requirement not recorded, e.g. in `install_requires`, so that pip et al. have a chance to resolve the required dependencies correctly?

**Comment by jaraco** [comment]
> Why is this dependency requirement not recorded, e.g. in install_requires, so that pip et al. have a chance to resolve the required dependencies correctly when installing the package?

Good question. I guess I've always treated Setuptools like an implicit dependency because it's always been implicitly supplied and implicitly required.

But perhaps it makes sense to declare the dependency. Yes, I think it does. Let's give that a try.
