### ISSUE TITLE
setup.py uses obsolete setup_requires

### ISSUE THREAD

**Issue by ezaquarii** [pytest-dev/pytest-runner#42]
setup_requires is broken for off-line builds. Recommended alternative is PEP 518:

https://www.python.org/dev/peps/pep-0518/

**Comment by jaraco** [comment]
In 51082f35441, pytest-runner now includes pyproject.toml, which satisfies PEP 517/518 where relevant. `setup_requires` is still supplied for backward-compatibility. I don't think there's anything else to be done.

**Comment by jaraco** [comment]
Releasing as 4.3
