### ISSUE TITLE
 extras argument can't be set to False in setup.cfg

### ISSUE THREAD

**Issue by tszumowski** [pytest-dev/pytest-runner#45]
# Reproduction
See attached setup.cfg file (Rename as setup.cfg)

[setup.cfg.example.txt](https://github.com/pytest-dev/pytest-runner/files/2895231/setup.cfg.example.txt)

# Description
If I have `extras` assigned under `[pytest]` in setup.cfg, it will always pull in extras, regardless of the setting. In the `setup.cfg` example, I have:
```
[options.extras_require]
tf = tensorflow
...

[pytest]
extras = False
```

Tensorflow always gets installed. According to [this issue in pyscaffold](https://github.com/pyscaffold/pyscaffold/issues/228), pytest-runner reads it as string `'False'` which evaluates to `True`.

**Comment by jaraco** [comment]
I think the problem you're describing is unrelated to `pytest-runner`, which is just a thin wrapper around the [pytest project](/pytest-dev/pytest). You should report the issue there.
