### ISSUE TITLE
setup.py test is going to be deprecated

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest-runner#50]
from https://github.com/pytest-dev/pytest/issues/5534

this project also relies on setuptools options that are now considered 'smells':

```
    setup_requires=[
        'pytest-runner',
    ],
    tests_require=[
        'pytest',
    ],
```

**Comment by graingert** [comment]
It may be worth considering what `pytest-runner`'s place is in a PEP517/PEP518 world

**Comment by graingert** [comment]
pytest no longer recommends pytest-runner. Is it a good idea to mark it for deprecation here?

**Comment by jaraco** [comment]
Yes, probably. I think I'd wait to officially deprecate this project until setuptools has officially deprecated the test command, but I'm also open to more information sooner. Would you be willing to draft the change?

**Comment by monokrome** [comment]
For those who have found this through pytest-runner, what is the new recommendation? Just running `py.test`?

**Comment by merwok** [comment]
Yes, run `pytest` directly, and/or from tox to get isolation, multiple Python versions, etc.
