### ISSUE TITLE
.whl file in pypi.org contains underscore instead of dash

### ISSUE THREAD

**Issue by ecederstrand** [pytest-dev/pytest-runner#53]
See https://pypi.org/project/pytest-runner/5.1/#files

This confuses pip when it is restricted to binary-only installs.

I get an error similar to https://github.com/pytest-dev/pytest-runner/issues/41

**Comment by jaraco** [comment]
There's nothing to be done here. Any issues lie with setuptools or pip.

**Comment by guzzijones** [comment]
yeah seeing the same issue here.  how did you manage to build the wheel file with the underscore?

**Comment by ecederstrand** [comment]
The problem I had turned out to be because we are using an internal PyPI proxy server. `pip --index-url` can be used to point pip at this proxy, but if a package has requirements in `setup_requires` or `tests_require`, then setuptools is tasked with installing the requirements, and setuptools does not respect the `--index-url` option.

To fix this, you need to create a [distutils.cfg](https://setuptools.readthedocs.io/en/latest/setuptools.html#id43) file with the following content:

```
[easy_install]
index-url = https://example.com/some-proxy/simple
```
